### ISSUE TITLE
It will be nice add Symfony Command for convert IP format from db to IPv4 and so on...

### ISSUE THREAD

**Issue by scippio** [darsyn/ip#13]
It will be nice add Symfony Command for convert IP format from db to IPv4 and so on. :)

**Comment by zanderbaldwin** [comment]
I personally think that creating such a command would be out of the context of this project; it seems overkill for a simple value-object.

The command would have to have access to not only the database connection, but also the EntityManager to get schema information (to figure out the primary key). Unless you could make it schema-agnostic, I would recommend against it.

**However,** a console command to convert IPs would be useful - however, perhaps it should piped in from standard input instead. That way any data source could be used, not just databases. An example of converting a database value would be something like:

```bash
mysql -sN -u root {databaseName} -e "SELECT ip FROM logins WHERE id = 13" | bin/console darsyn:ip:ntop
```

So I'll start writing that command (unless you want to have a shot at it, and add yourself as a contributor?)

---

As far as I can tell, there's no way of piping a single scalar value from either the `doctrine:query:dql` or `doctrine:query:sql` commands (using DQL would be super useful!); the results are returned formatted - but I'll continue researching.
