### ISSUE TITLE
Incorrect behaviour with IPv4-mapped IPv6 addresses

### ISSUE THREAD

**Issue by pascal-hofmann** [darsyn/ip#14]
::ffff:c000:280 (::ffff:192.0.2.128) represents the IPv4 address 192.0.2.128. A deprecated format for IPv4-compatible IPv6 addresses is ::c000:280 (::192.0.2.128). This library only supports the latter format.

**Comment by zanderbaldwin** [comment]
Sorry for taking so long to get this out, will release a new version once Travis CI build passes.
