### ISSUE TITLE
Add constant or helper method for IPv4 CIDR

### ISSUE THREAD

**Issue by zanderbaldwin** [darsyn/ip#16]
Add either a constant or a helper method for converting IPv4 CIDR to IPv6 CIDR which this library uses for improved semantics. Eg:

```php
<?php
use Darsyn\IP\IP;
$ip = new IP('127.0.0.1');

// Instead of:
$ip->getNetworkIp(96 + 12)

// Either (but a better constant name):
$ip->getNetworkIp(IP::CIDR4TO6 + 12)

// Or:
$ip->getNetworkIp(IP::cidr4to6(12))
```

If anyone reads this, what are you opinions over each method?

**Comment by JCMais** [comment]
+1 for the constant.
