### ISSUE TITLE
Better Handle IPv4 addresses in IPv6 notation.

### ISSUE THREAD

**Issue by zanbaldwin** [darsyn/ip#17]
- Better handle **IPv4-mapped IPv6 addresses** (`::ffff:7f00:1`) by returning IPv4 notation from `getShortAddress()`
- Start handling **6to4-derived addressing** (`2002:7f00:1::`) in the version methods, also returning IPv4 notation from `getShortAddress()`.
- Internally store IPv4 addresses in IPv4-mapped format.

**Comment by zanderbaldwin** [comment]
Work for this has started in the [`feature/mapped-derived`](https://github.com/darsyn/ip/tree/feature/mapped-derived) branch.

**N.B.** this will become version `4.0.0` due to the way IP addresses are stored internally being backwards-incompatible.
