### ISSUE TITLE
PostgreSQL 9.5 saves nothing

### ISSUE THREAD

**Issue by gigi** [darsyn/ip#28]
Hi! Thanx for your extension, but there something wrong with doctrine support. IP column is empty in the table after flush.
php-fpm7.0
postresql 9.5
Doctrine 2.5.5-DEV

Thank You!

**Comment by zanderbaldwin** [comment]
Thanks for the report, I'll take a look at it today!

**Comment by zanderbaldwin** [comment]
Sorry that this has taken so long, had a horrendously hectic summer. I've just fixed issue #29 and now working towards this. Both fixes will be released at the same time.

**Comment by zanderbaldwin** [comment]
This has been fixed in version `3.3.1` - sorry for the delay and thanks for reporting it!
