### ISSUE TITLE
Creating a caster for Symfony VarDumper

### ISSUE THREAD

**Issue by scuben** [darsyn/ip#37]
https://github.com/symfony/symfony/pull/25116

**Comment by zanbaldwin** [comment]
Whhaaaaaaaaaat. That's so awesome!

**Comment by zanbaldwin** [comment]
I'm hoping to release `4.0.0` in the first quarter of next year though (I'm currently writing the documentation for it slowly).
Would be amazing if you've got any feedback on it ([`4.0.0-alpha`](https://github.com/darsyn/ip/tree/4.0.0-alpha)) since there's quite a few changes!
