### ISSUE TITLE
Searching on IP Address

### ISSUE THREAD

**Issue by TheJenne18** [darsyn/ip#39]

**Comment by zanbaldwin** [comment]
I'll take a look at this at some point soon, the binary blob would be returned in this case - your database implementation might have a problem searching through binary data perhaps, or maybe something completely different entirely.

What database are you using? SQLite/MySQL/PostgreSQL?

**Comment by TheJenne18** [comment]
I already fixed the problem, symfony did something wrong in the migrations.
