### ISSUE TITLE
Some valid IPs are detected as invalid

### ISSUE THREAD

**Issue by minterior** [darsyn/ip#4]
Despite `filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4))` and `inet_pton($ip)` are not failing (thus, the IP is valid), after executing the code: 
```php
            $ip = current(unpack('a4', inet_pton($ip)));
            $ip = str_pad($ip, 16, "\0", STR_PAD_LEFT);
```
is failing with some IPs because the final str_len of $ip is 15 instead of 16.

Example IP: 37.152.208.254

**Comment by zanderbaldwin** [comment]
Nice catch, I'll add it to the tests and then have a look at a fix.

**Comment by zanderbaldwin** [comment]
Could you provide a small script that reproduces the error? I can't seem to find it.

Also, can you provide the PHP version, operating system, and whether you are running 32-bit or 64-bit PHP? There are known errors on 32-bit versions of PHP.

```php
use Darsyn\IP\IP;
require_once __DIR__ . '/vendor/autoload.php';
$address = '37.152.208.254';
$ip = new IP($address);
var_dump(
    IP::validate($address), // bool(true)
    strlen((string) $ip),   // int(16)
    $ip->getShortAddress(), // string(14) "37.152.208.254"
    $ip->getLongAddress()   // string(39) "0000:0000:0000:0000:0000:0000:2598:d0fe"
);
```

**Comment by minterior** [comment]
Using your exact code snippet I get this on my Virtual Machine Debian GNU/Linux 7.9 (wheezy):
```
bool(true)
int(15)
string(14) "37.152.208.254"
string(39) "0000:0000:0000:0000:0000:0000:2598:d0fe"
```

Info:
```
$ uname -a
Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u6 x86_64 GNU/Linux

$ php -v
PHP 5.5.30-1~dotdeb+7.1 (cli) (built: Oct  1 2015 17:38:39) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
```

**Comment by zanderbaldwin** [comment]
That is really weird. My best guess is that it has something to do with how PHP deals with `NUL` characters (`\0`) on certain environments - the fix you found would probably enable the library to work on earlier PHP versions too!
