### ISSUE TITLE
Automatically use the CIDR4TO6 constant for IPv4 addresses.

### ISSUE THREAD

**Issue by coudenysj** [darsyn/ip#41]
I was wondering if it would be feasible to automatically use the CIDR4TO6 if the current object holds a IPv4 address.

In the following snippet, the `IP::CIDR4TO6 +` could added in the `getNetworkIP` method (as we now the IP it holds is v4):
```
$ip = new IP('12.34.56.78');
// Get the network address of an IP address given a subnet mask.
$networkIp = $ip->getNetworkIP(IP::CIDR4TO6 + 19);
$networkIp->getShortAddress(); // string() "12.34.32.0"
```

**Comment by zanbaldwin** [comment]
This feature has been added in the [`Multi` class](https://github.com/darsyn/ip/blob/4.0.0-beta1/src/Version/Multi.php) for version 4 of `darsyn/ip`.

I'm almost ready to release version 4, but it's staying in beta until I can get enough people to review it (so far, no one has) - if you'd like to review it (please!) the take a look through the [documentation I wrote for it](https://github.com/darsyn/ip/tree/4.0.0-beta1/docs) and then optionally [check out the source code](https://github.com/darsyn/ip/tree/4.0.0-beta1/src). Any comments or criticism is welcome!

**Comment by coudenysj** [comment]
Got it. Thanks!

**Comment by zanbaldwin** [comment]
Stable version of `4.0.0` has been released. Closing.
