### ISSUE TITLE
__toString

### ISSUE THREAD

**Issue by FredDut** [darsyn/ip#60]
Hello,

Nice work.

Is it possible to add à __toString method in Multi entity ?
The __toString method should return $this->getProtocolAppropriateAddress(). 
Twig rendering and forms will be simpler with a __toString()

Regards

**Comment by zanbaldwin** [comment]
In the documentation it states that `__toString()` maps to the `getBinary()` method.

But then I realised that I never actually implemented that functionality. Thanks for pointing it out.

So yes, I'll add `__toString()` in the interface and then implement it with the most appropriate method in each of the version classes. Hopefully will have this done in the next couple of days.

**Comment by zanbaldwin** [comment]
Sorry it took me so long to get round to this, getting PHPUnit working for both 5.6 and 8.0 wasn't as easy as I thought it was going to be so I left it for a while and completely forgot to finish it until now.

Version `4.0.1` has been released which includes string casting.
